-- Basic
require('core.plugins')
require('core.mappings')
require('core.configs')

-- Plugins
require('plugins.treesitter')
require('plugins.venv-lsp')
require('plugins.lsp')
require('plugins.catppuccin')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.formatter')
require('plugins.toggleterm')
require('plugins.comment')
require('plugins.autopairs')
require('plugins.bufferline')
require('plugins.gitsigns')
require('plugins.lualine')
require('plugins.dashboard')
require('plugins.neotree')
require('plugins.lsp_signature')
